밑바닥부터 시작하는 딥러닝 2
# 1.1 수학과 파이썬 복습

## 백터와 행렬

In [1]:
import numpy as np
 
x = np.array([1, 2, 3])
print(x.__class__) # 클래스 이름
print(x.shape) # 형상(값 하나일 때는 뒤에 쉼표)
print(x.ndim) #차원 수

<class 'numpy.ndarray'>
(3,)
1


* 1차원, 원소 수가 3개인 벡터

In [2]:
W = np.array([[1, 2, 3], [4, 5, 6]])
print(W.shape) # 형상
print(W.ndim) #차원 수

(2, 3)
2


* 2차원 배열, 2 by 3행렬

## 행렬의 원소별 연산

In [3]:
W = np.array([[1, 2, 3], [4, 5, 6]])
X = np.array([[0, 1, 2], [3, 4, 5]])
print(W + X) #합
print("-" * 20)
print(X * X) #곱

[[ 1  3  5]
 [ 7  9 11]]
--------------------
[[ 0  1  4]
 [ 9 16 25]]


## 브로드캐스트

In [4]:
A = np.array([[1, 2], [3, 4]])
print(A * 10)

[[10 20]
 [30 40]]


In [5]:
A = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
print(A*b)

[[10 40]
 [30 80]]


## 벡터의 내적과 행렬의 곱

In [6]:
# 벡터의 내적
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

* 두 벡터가 얼마나 같은 방향을 향하고 있는가

In [7]:
# 행렬의 곱
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.matmul(A, B)

array([[19, 22],
       [43, 50]])

In [8]:
# 행렬의 곱 (np.dot도 가능. 1차원 배열일 때는 벡터의 내적을 계산하고, 2차원 배열일 떄는 행렬의 곱 계산)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

## 행렬 형상 확인

* 형상 확인: 행렬의 곱에서는 대응하는 차원의 원소 수를 일치시켜야 함